version: '3.3'

services:
  client:
    build:      
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    # ports:
      # - "3000:3000"    
  server:    
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/app
      - /app/node_modules   
    environment:
      - PORT=4000        
    # ports:
    #   - "4000:4000"  
  mongodb:
    container_name: mongo
    image: mongo
    volumes:
      - node:/data/db
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "7000:80"      

volumes:
  node:
    driver: local      